Update order
bitfinexcom/bfx-hf-server pull request #136
Opened 2021-12-02 12:08 UTC by avsek477

**_Task_**: https://app.asana.com/0/1125859137800433/1201427008884285
**_Reference for order update payload_**: https://docs.bitfinex.com/reference#ws-auth-input-order-update

**_Changes required in frontend_**: Add translation in `bfx-hf-ui-core`
```
"updatingOrderWithId": "Updating order (ID: {{orderId}})"
```

**_Request payload_**: 
```
dispatch(WSActions.send(['order.update', authToken, {
      id: 80039464518,
      amount: '2.00000000',
      price: '33000',
      flags: 64,
      meta: { make_visible: 1 },
}]))
```
- NOTE: payload for stop limit orders: 
```
{
   id: 80039464526,
   price: '32000',
   price_aux_limit: '34000',
   amount: '4'
}
```

2021-12-02 13:49 UTC, tarcisiozf commented on lib/ws_servers/api/handlers/on_order_update.js
> +    d(`sucessfully updated order [ID: ${orderId}]`)
```suggestion
    d(`successfully updated order [ID: ${orderId}]`)
```

typo

2021-12-02 13:49 UTC, tarcisiozf approved these changes
lgtm

2021-12-03 10:56 UTC, vitaliystoliarovcc requested changes

2021-12-03 10:56 UTC, vitaliystoliarovcc commented on lib/ws_servers/api/handlers/on_order_update.js
> +    return sendError(ws, 'No client open for Bitfinex', ['noClientOpenFor'])
i18n props are missing (`{ target: 'Bitfinex' }`)

2021-12-03 11:09 UTC, avsek477 commented on lib/ws_servers/api/handlers/on_order_update.js
> +    return sendError(ws, 'No client open for Bitfinex', ['noClientOpenFor'])
done

2021-12-03 12:25 UTC, vitaliystoliarovcc approved these changes

2021-12-09 14:02 UTC, merged