add recurring algo order submit handler
bitfinexcom/bfx-hf-server pull request #217
Opened 2023-01-26 17:00 UTC by arifjmamun

2023-01-27 21:38 UTC, dmytroshch commented
Let's use existed `algo...` messages and invoke related recurring ao handlers from ao handlers?

2023-01-27 21:44 UTC, dmytroshch commented
https://github.com/bitfinexcom/bfx-hf-server/blob/master/lib/ws_servers/api/handlers/on_algo_order_submit.js#L31-L33
check if `id === 'bfx-hf-recurring'`, if it is, just invoke this [handler](https://github.com/bitfinexcom/bfx-hf-server/pull/217/files#diff-1bf81916292b69f80b8c687a1ad02cef83453f0501cd6e9c6acc07eec809d3bd) and save ao to local db (algos.json)

2023-01-27 21:50 UTC, dmytroshch commented
or, for example, for cancelling
https://github.com/bitfinexcom/bfx-hf-server/blob/master/lib/ws_servers/api/handlers/on_algo_order_cancel.js#L25
check if requested order is recurring ao (in local db) and invoke [hanlder](https://github.com/bitfinexcom/bfx-hf-server/pull/217/files#diff-609c7271e20feeecc93674465d59d73b84758a2f3ea719b1498f46988b81bfc9)

2023-01-28 10:14 UTC, arifjmamun commented
> also, for example, for cancelling https://github.com/bitfinexcom/bfx-hf-server/blob/master/lib/ws_servers/api/algos/algo_worker.js#L296 check if requested order is recurring ao (in local db) and invoke [handler](https://github.com/bitfinexcom/bfx-hf-server/pull/217/files#diff-609c7271e20feeecc93674465d59d73b84758a2f3ea719b1498f46988b81bfc9)

@tarcisiozf is it make sense to call other handlers conditionally based on `aoID === 'bfx-hf-recurring'`? the recurring AOs will live outside of hf-server/hf-hosted, still do we need to store them locally in `algos.json`? Is it going to be better if it merged into existing algo handlers?

2023-01-30 16:07 UTC, tarcisiozf commented on lib/ws_servers/api/handlers/on_recurring_algo_order_load_list.js
> +    return
I think is useful to send an error message

2023-02-01 21:56 UTC, dmytroshch commented
please update algo lib to [v4.17.0](https://github.com/bitfinexcom/bfx-hf-algo/releases/tag/v4.17.0) and use `Recurring.id` instead of 'bfx-recurring'

2023-02-02 09:15 UTC, arifjmamun commented
> 
please check the file for algo lib v4.17.0: https://github.com/bitfinexcom/bfx-hf-server/pull/217/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

2023-02-02 12:44 UTC, tarcisiozf approved these changes

2023-02-02 12:48 UTC, tarcisiozf requested changes

2023-02-02 13:29 UTC, arifjmamun commented on lib/ws_servers/api/index.js
> +        'recurring_algo_order.submit': onRecurringAlgoOrderSubmit,
yes, we don't need to expose these additional messages. I am going to update it.

2023-02-15 06:02 UTC, arifjmamun commented on lib/ws_servers/api/handlers/on_recurring_algo_order_load_list.js
> +    AlgoOrder.set({ ...mappedRecurringAO, state: JSON.stringify(mappedRecurringAO.state) })
it is **asynchronous** method and its need to be **awaited**.

2023-02-15 12:40 UTC, arifjmamun reviewed
Looks good!

2023-02-20 23:13 UTC, dmytroshch commented
Works properly on FE

2023-02-21 11:48 UTC, tarcisiozf approved these changes

2023-02-21 11:54 UTC, merged